/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CreateProjectRouteImport } from './routes/create-project'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as WorkflowRunsExecutionIdRouteImport } from './routes/workflow-runs/$executionId'
import { Route as TasksSessionIdRouteImport } from './routes/tasks/$sessionId'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as SettingsExperimentsRouteImport } from './routes/settings/experiments'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProcessesProcessIdRouteImport } from './routes/processes/$processId'
import { Route as FoldersSplatRouteImport } from './routes/folders/$'
import { Route as FilesSplatRouteImport } from './routes/files/$'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdCommitRouteImport } from './routes/projects/$projectId/commit'
import { Route as ProjectsProjectIdCommitsHashRouteImport } from './routes/projects/$projectId/commits.$hash'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProjectRoute = CreateProjectRouteImport.update({
  id: '/create-project',
  path: '/create-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRunsExecutionIdRoute = WorkflowRunsExecutionIdRouteImport.update({
  id: '/workflow-runs/$executionId',
  path: '/workflow-runs/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSessionIdRoute = TasksSessionIdRouteImport.update({
  id: '/tasks/$sessionId',
  path: '/tasks/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExperimentsRoute = SettingsExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesProcessIdRoute = ProcessesProcessIdRouteImport.update({
  id: '/processes/$processId',
  path: '/processes/$processId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersSplatRoute = FoldersSplatRouteImport.update({
  id: '/folders/$',
  path: '/folders/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCommitRoute = ProjectsProjectIdCommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdCommitsHashRoute =
  ProjectsProjectIdCommitsHashRouteImport.update({
    id: '/commits/$hash',
    path: '/commits/$hash',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-project': typeof CreateProjectRoute
  '/settings': typeof SettingsRouteWithChildren
  '/files/$': typeof FilesSplatRoute
  '/folders/$': typeof FoldersSplatRoute
  '/processes/$processId': typeof ProcessesProcessIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/experiments': typeof SettingsExperimentsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/tasks/$sessionId': typeof TasksSessionIdRoute
  '/workflow-runs/$executionId': typeof WorkflowRunsExecutionIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectId/commit': typeof ProjectsProjectIdCommitRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/commits/$hash': typeof ProjectsProjectIdCommitsHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-project': typeof CreateProjectRoute
  '/files/$': typeof FilesSplatRoute
  '/folders/$': typeof FoldersSplatRoute
  '/processes/$processId': typeof ProcessesProcessIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/experiments': typeof SettingsExperimentsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/tasks/$sessionId': typeof TasksSessionIdRoute
  '/workflow-runs/$executionId': typeof WorkflowRunsExecutionIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/$projectId/commit': typeof ProjectsProjectIdCommitRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/commits/$hash': typeof ProjectsProjectIdCommitsHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-project': typeof CreateProjectRoute
  '/settings': typeof SettingsRouteWithChildren
  '/files/$': typeof FilesSplatRoute
  '/folders/$': typeof FoldersSplatRoute
  '/processes/$processId': typeof ProcessesProcessIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/experiments': typeof SettingsExperimentsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/tasks/$sessionId': typeof TasksSessionIdRoute
  '/workflow-runs/$executionId': typeof WorkflowRunsExecutionIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectId/commit': typeof ProjectsProjectIdCommitRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/commits/$hash': typeof ProjectsProjectIdCommitsHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-project'
    | '/settings'
    | '/files/$'
    | '/folders/$'
    | '/processes/$processId'
    | '/projects/$projectId'
    | '/settings/about'
    | '/settings/api-keys'
    | '/settings/experiments'
    | '/settings/shortcuts'
    | '/settings/theme'
    | '/tasks/$sessionId'
    | '/workflow-runs/$executionId'
    | '/workflows/$workflowId'
    | '/settings/'
    | '/projects/$projectId/commit'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/commits/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-project'
    | '/files/$'
    | '/folders/$'
    | '/processes/$processId'
    | '/settings/about'
    | '/settings/api-keys'
    | '/settings/experiments'
    | '/settings/shortcuts'
    | '/settings/theme'
    | '/tasks/$sessionId'
    | '/workflow-runs/$executionId'
    | '/workflows/$workflowId'
    | '/settings'
    | '/projects/$projectId/commit'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/commits/$hash'
  id:
    | '__root__'
    | '/'
    | '/create-project'
    | '/settings'
    | '/files/$'
    | '/folders/$'
    | '/processes/$processId'
    | '/projects/$projectId'
    | '/settings/about'
    | '/settings/api-keys'
    | '/settings/experiments'
    | '/settings/shortcuts'
    | '/settings/theme'
    | '/tasks/$sessionId'
    | '/workflow-runs/$executionId'
    | '/workflows/$workflowId'
    | '/settings/'
    | '/projects/$projectId/commit'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/commits/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateProjectRoute: typeof CreateProjectRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  FilesSplatRoute: typeof FilesSplatRoute
  FoldersSplatRoute: typeof FoldersSplatRoute
  ProcessesProcessIdRoute: typeof ProcessesProcessIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  TasksSessionIdRoute: typeof TasksSessionIdRoute
  WorkflowRunsExecutionIdRoute: typeof WorkflowRunsExecutionIdRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-project': {
      id: '/create-project'
      path: '/create-project'
      fullPath: '/create-project'
      preLoaderRoute: typeof CreateProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-runs/$executionId': {
      id: '/workflow-runs/$executionId'
      path: '/workflow-runs/$executionId'
      fullPath: '/workflow-runs/$executionId'
      preLoaderRoute: typeof WorkflowRunsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$sessionId': {
      id: '/tasks/$sessionId'
      path: '/tasks/$sessionId'
      fullPath: '/tasks/$sessionId'
      preLoaderRoute: typeof TasksSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/experiments': {
      id: '/settings/experiments'
      path: '/experiments'
      fullPath: '/settings/experiments'
      preLoaderRoute: typeof SettingsExperimentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/$processId': {
      id: '/processes/$processId'
      path: '/processes/$processId'
      fullPath: '/processes/$processId'
      preLoaderRoute: typeof ProcessesProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$': {
      id: '/folders/$'
      path: '/folders/$'
      fullPath: '/folders/$'
      preLoaderRoute: typeof FoldersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/commit': {
      id: '/projects/$projectId/commit'
      path: '/commit'
      fullPath: '/projects/$projectId/commit'
      preLoaderRoute: typeof ProjectsProjectIdCommitRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/commits/$hash': {
      id: '/projects/$projectId/commits/$hash'
      path: '/commits/$hash'
      fullPath: '/projects/$projectId/commits/$hash'
      preLoaderRoute: typeof ProjectsProjectIdCommitsHashRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsExperimentsRoute: typeof SettingsExperimentsRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsExperimentsRoute: SettingsExperimentsRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdCommitRoute: typeof ProjectsProjectIdCommitRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdCommitsHashRoute: typeof ProjectsProjectIdCommitsHashRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdCommitRoute: ProjectsProjectIdCommitRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdCommitsHashRoute: ProjectsProjectIdCommitsHashRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateProjectRoute: CreateProjectRoute,
  SettingsRoute: SettingsRouteWithChildren,
  FilesSplatRoute: FilesSplatRoute,
  FoldersSplatRoute: FoldersSplatRoute,
  ProcessesProcessIdRoute: ProcessesProcessIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  TasksSessionIdRoute: TasksSessionIdRoute,
  WorkflowRunsExecutionIdRoute: WorkflowRunsExecutionIdRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
